# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.13.2]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v2
            with:
              heroku_api_key: ${{secrets.HEROKU_API_KEY}}
              heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
              heroku_email: ${{secretes.HEROKU_EMAIL}}
              db_production: ${{secrets.DB_PRODUCTION}}
              node_env: ${{secrets.NODE_ENV}}
              jwt_secret_key: ${{secrets.JWT_SECRET_KEY}}
              node-version: ${{ matrix.node-version }}
          - run: npm ci
          - run: npm run build --if-present
#           - run: npm run test
